name: Test Homebrew Formula

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Test formula installation
      run: |
        brew install --formula ./Formula/diff-gitignore-filter.rb

    - name: Test formula functionality
      run: |
        # Test that the binary was installed
        which diff-gitignore-filter

        # Test basic help output
        diff-gitignore-filter --help

        # Test version output
        diff-gitignore-filter --version || true

    - name: Test formula audit
      run: |
        brew audit --strict diff-gitignore-filter

    - name: Test formula style
      run: |
        brew style ./Formula/diff-gitignore-filter.rb
